"""
app/services/owner_pdf_service.py
OWNER-PDF-1 — Owner WhatsApp PDF report formatters.

Four report types, provider-agnostic:
  build_period_summary_pdf()
  build_lead_pipeline_pdf()
  build_orders_fulfilment_pdf()
  build_comparison_pdf()

Each returns (pdf_bytes | None, meta: dict). meta always includes "label" on
success; on failure meta includes "reason" and pdf_bytes is None.

Design (per OWNER-PDF-1 spec):
  - Provider-agnostic: report adapts to whichever providers are connected.
  - Non-Shopify safe: all four report types work without Shopify.
  - Each new provider adds one _render_{provider}_section() function only.

Uses the same provider registry as owner_query_service.py — get_provider(),
get_connected_providers(), get_provider_capabilities() — and never reads
provider-owned data through any interface other than get_summary()/search(),
with one deliberate exception: the lead_pipeline full-record export needs
`assigned_to` (rep), which no provider .search()/.get_summary() response
currently carries. That one path queries `leads` + `users` directly, using
the exact same table/column shape OpsraOrdersProvider already relies on in
opsra_orders_provider_service.py (org_id/deleted_at/created_at filters,
full_name/whatsapp/phone/source/score/stage/last_activity_at columns).

PDF engine: WeasyPrint (already a project dependency — see
report_delivery_worker.py / RPT-1A).

S14: every formatter returns (None, {'reason': ...}) on failure, never raises.
Pattern 29: load_dotenv() at module level.
"""
from __future__ import annotations

import logging
from datetime import date, datetime, timedelta, timezone
from typing import Any, Optional

from dotenv import load_dotenv

from app.integrations.registry import (
    get_provider,
    get_connected_providers,
    get_provider_capabilities,
)

load_dotenv()

logger = logging.getLogger(__name__)

# Placeholder brand colour — swap for the exact ds.teal hex used across the
# frontend (Pattern 11/12/13 modules all reference ds.teal; the token's raw
# hex value wasn't in any of the files reviewed this session).
_BRAND_TEAL = "#0d9488"
_GENERATED_FOOTER = "Generated by Opsra"

_STAGE_ORDER = [
    "new", "contacted", "meeting_done", "proposal_sent",
    "converted", "lost", "not_ready",
]
_SCORE_ORDER = ["hot", "warm", "cold", "unscored"]


# ── Shared helpers ───────────────────────────────────────────────────────────

def _human_range(date_from: Optional[date], date_to: Optional[date]) -> str:
    if not date_from or not date_to:
        return "All time"
    if date_from == date_to:
        return date_from.strftime("%-d %b %Y")
    return f"{date_from.strftime('%-d %b %Y')} \u2013 {date_to.strftime('%-d %b %Y')}"


def _prior_period(date_from: date, date_to: date) -> tuple[date, date]:
    """
    Returns the immediately preceding period of equal length, e.g.
    1-30 Jun -> 1-31 May (30-day window shifted back 30 days).

    Used only by build_comparison_pdf. The pdf_report routing schema (see
    OWNER-PDF-1 spec) carries a single date_from/date_to even when
    report_type=comparison — unlike the separate "compare" action in
    owner_query_service.py, which resolves explicit period_a/period_b via
    the Sonnet routing call. This formatter treats date_from/date_to as the
    current period and derives the prior period itself.
    """
    span = (date_to - date_from).days + 1
    prior_to = date_from - timedelta(days=1)
    prior_from = prior_to - timedelta(days=span - 1)
    return prior_from, prior_to


def _stage_sort_key(stage: str) -> int:
    try:
        return _STAGE_ORDER.index(stage)
    except ValueError:
        return len(_STAGE_ORDER)


def _score_sort_key(score: str) -> int:
    try:
        return _SCORE_ORDER.index(score)
    except ValueError:
        return len(_SCORE_ORDER)


def _money(value: Any) -> str:
    try:
        return f"\u20a6{float(value or 0):,.2f}"
    except Exception:
        return "\u20a60.00"


def _render_pdf(html: str) -> Optional[bytes]:
    """S14: returns None on any WeasyPrint failure."""
    try:
        from weasyprint import HTML
        return HTML(string=html).write_pdf()
    except Exception as exc:
        logger.error("owner_pdf_service._render_pdf failed: %s", exc)
        return None


def _base_html(title: str, subtitle: str, body_html: str) -> str:
    generated_at = datetime.now(timezone.utc).strftime("%-d %b %Y %H:%M UTC")
    return f"""
    <html>
    <head>
    <meta charset="utf-8">
    <style>
      @page {{ size: A4; margin: 2cm; }}
      body {{ font-family: 'Helvetica', 'Arial', sans-serif; color: #1a1a1a; font-size: 11pt; }}
      h1 {{ color: {_BRAND_TEAL}; font-size: 20pt; margin-bottom: 2px; }}
      h2 {{ color: {_BRAND_TEAL}; font-size: 14pt; border-bottom: 1px solid #e0e0e0;
            padding-bottom: 4px; margin-top: 24px; }}
      .subtitle {{ color: #666; font-size: 10pt; margin-bottom: 20px; }}
      table {{ width: 100%; border-collapse: collapse; margin-top: 8px; font-size: 9.5pt; }}
      th {{ background: {_BRAND_TEAL}; color: white; text-align: left; padding: 6px 8px; }}
      td {{ padding: 5px 8px; border-bottom: 1px solid #eee; }}
      tr:nth-child(even) {{ background: #f7f7f7; }}
      .stat-row {{ display: block; margin: 4px 0; }}
      .stat-label {{ color: #666; }}
      .stat-value {{ font-weight: bold; font-size: 13pt; }}
      .warning {{ background: #fff8e1; border-left: 3px solid #f9a825; padding: 8px 12px;
                  margin: 12px 0; font-size: 9.5pt; }}
      .footer {{ margin-top: 30px; color: #999; font-size: 8pt; text-align: center; }}
    </style>
    </head>
    <body>
      <h1>{title}</h1>
      <div class="subtitle">{subtitle}</div>
      {body_html}
      <div class="footer">{_GENERATED_FOOTER} \u2014 {generated_at}</div>
    </body>
    </html>
    """


def _stat_block(label: str, value: Any) -> str:
    return (
        f'<div class="stat-row"><span class="stat-label">{label}: </span>'
        f'<span class="stat-value">{value}</span></div>'
    )


def _warning_block(text: str) -> str:
    return f'<div class="warning">\u26a0\ufe0f {text}</div>'


def _get_org_name(db: Any, org_id: str) -> str:
    """S14: returns 'Your Business' on any failure."""
    try:
        result = (
            db.table("organisations")
            .select("name")
            .eq("id", org_id)
            .maybe_single()
            .execute()
        )
        data = result.data
        if isinstance(data, list):
            data = data[0] if data else None
        return (data or {}).get("name") or "Your Business"
    except Exception:
        return "Your Business"


def _resolve_provider_names(db: Any, org_id: str, provider_names: list[str]) -> list[str]:
    """
    Routing may supply an empty/partial provider list. Fall back to all
    connected providers for this org. S14: returns [] on failure.
    """
    if provider_names:
        return provider_names
    return get_connected_providers(db, org_id)


# ── period_summary ───────────────────────────────────────────────────────────

def build_period_summary_pdf(
    db: Any,
    org_id: str,
    provider_names: list[str],
    date_from: Optional[date],
    date_to: Optional[date],
) -> tuple[Optional[bytes], dict]:
    """
    One section per connected provider. Leads (opsra_orders) always
    included, per the OWNER-PDF-1 provider coverage matrix.
    S14: returns (None, {'reason': ...}) if nothing could be retrieved.
    """
    try:
        if not date_from or not date_to:
            return None, {"reason": "No date range was resolved for this report."}

        providers = _resolve_provider_names(db, org_id, provider_names)
        if "opsra_orders" not in providers:
            providers = ["opsra_orders"] + providers

        org_name = _get_org_name(db, org_id)
        period_label = _human_range(date_from, date_to)
        sections_html = ""
        any_section = False
        highlights: list[str] = []

        for name in providers:
            provider = get_provider(name)
            if provider is None:
                continue
            data = provider.get_summary(db, org_id, date_from, date_to)
            if not isinstance(data, dict) or not data.get("available"):
                continue
            any_section = True
            caps = get_provider_capabilities(name)
            label = caps.get("label", name.replace("_", " ").title())
            emoji = caps.get("emoji", "\U0001F4CA")

            section_html, section_highlights = _render_provider_section(name, label, emoji, data)
            sections_html += section_html
            highlights.extend(section_highlights)

        if not any_section:
            return None, {"reason": "No data was available for that period."}

        highlights_html = ""
        if highlights:
            items = "".join(f"<li>{h}</li>" for h in highlights)
            highlights_html = f"<h2>Highlights</h2><ul>{items}</ul>"

        body = sections_html + highlights_html
        html = _base_html(f"{org_name} \u2014 Period Summary", period_label, body)
        pdf_bytes = _render_pdf(html)
        if not pdf_bytes:
            return None, {"reason": "PDF generation failed."}

        return pdf_bytes, {"label": f"Period Summary ({period_label})"}

    except Exception as exc:
        logger.error("build_period_summary_pdf failed org=%s: %s", org_id, exc)
        return None, {"reason": "Could not build the report right now."}


def _render_provider_section(name: str, label: str, emoji: str, data: dict) -> tuple[str, list[str]]:
    """
    Dispatch to the provider-specific renderer. One _render_{provider}_section
    function per provider, per OWNER-PDF-1 design principle — adding a new
    provider (zoho_books, gmail, flutterwave) means adding one function here
    and one line to `renderers`, nothing else in this module changes.
    Returns (html, highlight_strings).
    """
    renderers = {
        "opsra_orders": _render_opsra_orders_section,
        "paystack":     _render_paystack_section,
        "shopify":      _render_shopify_section,
    }
    renderer = renderers.get(name, _render_generic_section)
    return renderer(label, emoji, data)


def _render_opsra_orders_section(label: str, emoji: str, data: dict) -> tuple[str, list[str]]:
    html = f"<h2>{emoji} {label}</h2>"
    html += _stat_block("Total leads", data.get("total_leads", 0))
    html += _stat_block("Converted", data.get("converted_leads", 0))
    html += _stat_block("Conversion rate", f"{data.get('conversion_rate_pct', 0)}%")
    best_source = data.get("best_converting_source")
    if best_source:
        html += _stat_block(
            "Best converting source",
            f"{best_source} ({data.get('best_source_conversion_pct', 0)}%)",
        )
    by_source = data.get("leads_by_source") or {}
    if by_source:
        rows = "".join(f"<tr><td>{k}</td><td>{v}</td></tr>" for k, v in by_source.items())
        html += f"<table><tr><th>Source</th><th>Leads</th></tr>{rows}</table>"
    if "total_wa_sessions" in data:
        html += _stat_block("WhatsApp orders", data.get("total_wa_sessions", 0))
        html += _stat_block("Completed WhatsApp orders", data.get("completed_wa_orders", 0))
        html += _stat_block("WhatsApp commerce revenue", _money(data.get("wa_commerce_revenue_ngn")))
    if data.get("data_warning"):
        html += _warning_block(data["data_warning"])

    highlights = []
    if data.get("total_leads"):
        highlights.append(
            f"{data['total_leads']} leads, {data.get('conversion_rate_pct', 0)}% conversion rate."
        )
    return html, highlights


def _render_paystack_section(label: str, emoji: str, data: dict) -> tuple[str, list[str]]:
    html = f"<h2>{emoji} {label}</h2>"
    revenue = data.get("total_revenue_ngn", 0) or 0
    html += _stat_block("Total revenue", _money(revenue))
    if "total_transactions" in data:
        html += _stat_block("Transactions", data.get("total_transactions", 0))
    if "total_payments" in data:
        html += _stat_block("Payments", data.get("total_payments", 0))
        html += _stat_block("Active subscriptions", data.get("active_subscriptions", 0))
    if data.get("data_warning"):
        html += _warning_block(data["data_warning"])

    highlights = []
    if revenue:
        highlights.append(f"{_money(revenue)} in revenue this period.")
    return html, highlights


def _render_shopify_section(label: str, emoji: str, data: dict) -> tuple[str, list[str]]:
    html = f"<h2>{emoji} {label}</h2>"
    html += _stat_block("Total revenue", _money(data.get("total_revenue_ngn")))
    html += _stat_block("Orders", data.get("total_orders", 0))
    html += _stat_block("Average order value", _money(data.get("average_order_value_ngn")))
    html += _stat_block("Fulfilment rate", f"{data.get('fulfilment_rate_pct', 0)}%")
    html += _stat_block("Unfulfilled orders", data.get("unfulfilled_orders", 0))
    top_products = data.get("top_products") or []
    if top_products:
        _dash = "\u2014"
        rows = "".join(
            f"<tr><td>{p.get('title') or _dash}</td><td>{p.get('units_sold', 0)}</td>"
            f"<td>{_money(p.get('revenue_ngn'))}</td></tr>"
            for p in top_products
        )
        html += f"<table><tr><th>Product</th><th>Units</th><th>Revenue</th></tr>{rows}</table>"
    if data.get("data_warning"):
        html += _warning_block(data["data_warning"])

    highlights = []
    if data.get("total_orders"):
        highlights.append(
            f"{data['total_orders']} Shopify orders, {data.get('fulfilment_rate_pct', 0)}% fulfilled."
        )
    return html, highlights


def _render_generic_section(label: str, emoji: str, data: dict) -> tuple[str, list[str]]:
    """Fallback renderer for any future provider without a dedicated function."""
    html = f"<h2>{emoji} {label}</h2>"
    numeric_fields = {
        k: v for k, v in data.items()
        if isinstance(v, (int, float)) and k != "available"
    }
    for k, v in numeric_fields.items():
        html += _stat_block(k.replace("_", " ").title(), v)
    return html, []


# ── lead_pipeline ────────────────────────────────────────────────────────────

def _fetch_lead_pipeline_rows(db: Any, org_id: str, date_from: date, date_to: date) -> list[dict]:
    """
    Full lead list for the lead_pipeline report: name, phone, source, score,
    stage, last activity, assigned rep. Sorted by stage then score.

    Queries `leads` directly (same table/column shape OpsraOrdersProvider
    already uses in get_summary()/search()) plus a batch lookup against
    `users` for assigned_to -> full_name, because no provider .search()/
    .get_summary() response currently carries assigned_to.
    S14: returns [] on any failure.
    """
    try:
        from_iso = date_from.isoformat()
        to_iso = date_to.isoformat() + "T23:59:59"

        result = (
            db.table("leads")
            .select(
                "id, full_name, phone, whatsapp, source, score, stage, "
                "assigned_to, last_activity_at, created_at"
            )
            .eq("org_id", org_id)
            .is_("deleted_at", "null")
            .gte("created_at", from_iso)
            .lte("created_at", to_iso)
            .execute()
        )
        leads = result.data or []
        if not leads:
            return []

        rep_ids = {l["assigned_to"] for l in leads if l.get("assigned_to")}
        rep_names: dict[str, str] = {}
        if rep_ids:
            try:
                users_result = (
                    db.table("users")
                    .select("id, full_name")
                    .in_("id", list(rep_ids))
                    .execute()
                )
                for u in (users_result.data or []):
                    rep_names[u["id"]] = u.get("full_name") or "\u2014"
            except Exception as exc:
                logger.warning(
                    "_fetch_lead_pipeline_rows: rep name lookup failed org=%s: %s",
                    org_id, exc,
                )

        rows = []
        for l in leads:
            rows.append({
                "name":          l.get("full_name") or "\u2014",
                "phone":         l.get("whatsapp") or l.get("phone") or "\u2014",
                "source":        l.get("source") or "\u2014",
                "score":         l.get("score") or "unscored",
                "stage":         l.get("stage") or "new",
                "last_activity": (l.get("last_activity_at") or l.get("created_at") or "")[:10],
                "assigned_rep":  rep_names.get(l.get("assigned_to"), "Unassigned"),
            })

        rows.sort(key=lambda r: (_stage_sort_key(r["stage"]), _score_sort_key(r["score"])))
        return rows
    except Exception as exc:
        logger.warning("_fetch_lead_pipeline_rows failed org=%s: %s", org_id, exc)
        return []


def build_lead_pipeline_pdf(
    db: Any,
    org_id: str,
    provider_names: list[str],
    date_from: Optional[date],
    date_to: Optional[date],
) -> tuple[Optional[bytes], dict]:
    """
    Summary stats + full lead list. opsra_orders is always the source —
    leads live in Opsra's own tables regardless of which providers are
    connected, and it's marked "primary" for lead_pipeline on every org in
    the OWNER-PDF-1 provider coverage matrix.
    """
    try:
        if not date_from or not date_to:
            return None, {"reason": "No date range was resolved for this report."}

        provider = get_provider("opsra_orders")
        if provider is None:
            return None, {"reason": "Leads data source is not available."}

        summary = provider.get_summary(db, org_id, date_from, date_to)
        rows = _fetch_lead_pipeline_rows(db, org_id, date_from, date_to)

        summary_available = isinstance(summary, dict) and summary.get("available")
        if not summary_available and not rows:
            return None, {"reason": "No lead data was available for that period."}

        org_name = _get_org_name(db, org_id)
        period_label = _human_range(date_from, date_to)

        body = "<h2>\U0001F4CA Summary</h2>"
        if summary_available:
            body += _stat_block("Total leads", summary.get("total_leads", 0))
            body += _stat_block("Converted", summary.get("converted_leads", 0))
            body += _stat_block("Conversion rate", f"{summary.get('conversion_rate_pct', 0)}%")

        body += "<h2>\U0001F4CB Lead Pipeline</h2>"
        if rows:
            table_rows = "".join(
                f"<tr><td>{r['name']}</td><td>{r['phone']}</td><td>{r['source']}</td>"
                f"<td>{r['score']}</td><td>{r['stage']}</td><td>{r['last_activity']}</td>"
                f"<td>{r['assigned_rep']}</td></tr>"
                for r in rows
            )
            body += (
                "<table><tr><th>Name</th><th>Phone</th><th>Source</th>"
                "<th>Score</th><th>Stage</th><th>Last Activity</th><th>Assigned Rep</th></tr>"
                f"{table_rows}</table>"
            )
        else:
            body += "<p>No leads recorded for this period.</p>"

        html = _base_html(f"{org_name} \u2014 Lead Pipeline Report", period_label, body)
        pdf_bytes = _render_pdf(html)
        if not pdf_bytes:
            return None, {"reason": "PDF generation failed."}

        return pdf_bytes, {"label": f"Lead Pipeline Report ({period_label})"}

    except Exception as exc:
        logger.error("build_lead_pipeline_pdf failed org=%s: %s", org_id, exc)
        return None, {"reason": "Could not build the report right now."}


# ── orders_fulfilment ────────────────────────────────────────────────────────

def build_orders_fulfilment_pdf(
    db: Any,
    org_id: str,
    provider_names: list[str],
    date_from: Optional[date],
    date_to: Optional[date],
) -> tuple[Optional[bytes], dict]:
    """
    Shopify orgs: live order list from the Shopify Admin API via
    ShopifyProvider.search(). Non-Shopify commerce orgs (whatsapp_sales_mode
    in bot/ai_agent): commerce_sessions via OpsraOrdersProvider.search("order").
    Consultative orgs (whatsapp_sales_mode = human, no Shopify): converted
    leads as a proxy via OpsraOrdersProvider.search("converted") — exactly
    per the OWNER-PDF-1 provider coverage matrix.
    """
    try:
        org_name = _get_org_name(db, org_id)
        period_label = _human_range(date_from, date_to) if (date_from and date_to) else "Recent"

        providers = _resolve_provider_names(db, org_id, provider_names)
        rows: list[list[str]] = []
        columns: list[str] = []
        mode = ""

        if "shopify" in providers:
            shopify = get_provider("shopify")
            if shopify:
                results = shopify.search(db, org_id, "", limit=200)
                if results:
                    mode = "shopify"
                    columns = ["Order", "Customer", "Total", "Financial", "Fulfilment", "Date"]
                    rows = [
                        [
                            r.get("order_name", "\u2014"),
                            r.get("customer_name", "\u2014"),
                            _money(r.get("total_ngn")),
                            r.get("financial_status", "\u2014"),
                            r.get("fulfillment_status", "\u2014"),
                            r.get("created_at", "\u2014"),
                        ]
                        for r in results
                    ]

        if not rows:
            org_result = (
                db.table("organisations")
                .select("whatsapp_sales_mode")
                .eq("id", org_id)
                .maybe_single()
                .execute()
            )
            org_data = org_result.data
            if isinstance(org_data, list):
                org_data = org_data[0] if org_data else None
            wa_mode = (org_data or {}).get("whatsapp_sales_mode") or "human"

            opsra_orders = get_provider("opsra_orders")
            if opsra_orders:
                if wa_mode in ("bot", "ai_agent"):
                    results = opsra_orders.search(db, org_id, "order", limit=200)
                    if results:
                        mode = "commerce"
                        columns = ["Status", "Phone", "Items", "Total", "Date"]
                        rows = [
                            [
                                r.get("status", "\u2014"),
                                r.get("phone_number", "\u2014"),
                                r.get("items", "\u2014"),
                                _money(r.get("total_ngn")),
                                r.get("created_at", "\u2014"),
                            ]
                            for r in results
                        ]
                else:
                    results = opsra_orders.search(db, org_id, "converted", limit=200)
                    if results:
                        mode = "consultative (converted leads)"
                        columns = ["Name", "Phone", "Source", "Business", "Date"]
                        rows = [
                            [
                                r.get("name", "\u2014"),
                                r.get("phone", "\u2014"),
                                r.get("source", "\u2014"),
                                r.get("business", "\u2014"),
                                r.get("created_at", "\u2014"),
                            ]
                            for r in results
                        ]

        if not rows:
            return None, {"reason": "No order data was available for that period."}

        body = f"<h2>\U0001F4E6 Orders ({mode.replace('_', ' ').title()})</h2>"
        header_row = "".join(f"<th>{c}</th>" for c in columns)
        body_rows = "".join(
            "<tr>" + "".join(f"<td>{cell}</td>" for cell in row) + "</tr>"
            for row in rows
        )
        body += f"<table><tr>{header_row}</tr>{body_rows}</table>"

        html = _base_html(f"{org_name} \u2014 Orders & Fulfilment Report", period_label, body)
        pdf_bytes = _render_pdf(html)
        if not pdf_bytes:
            return None, {"reason": "PDF generation failed."}

        return pdf_bytes, {"label": f"Orders & Fulfilment Report ({period_label})"}

    except Exception as exc:
        logger.error("build_orders_fulfilment_pdf failed org=%s: %s", org_id, exc)
        return None, {"reason": "Could not build the report right now."}


# ── comparison ────────────────────────────────────────────────────────────────

def _generate_comparison_summary(db: Any, org_id: str, metric_lines: list[str]) -> str:
    """
    Haiku-generated executive summary paragraph, per OWNER-PDF-1 spec.
    Reuses the existing Claude-calling + usage-logging infra from
    owner_query_service.py (lazy import — Pattern 63, avoids a circular
    import since owner_query_service.py is the caller of this module's
    sibling worker at dispatch time, not of this module directly).
    S14: returns '' on any failure — the PDF still renders without it.
    """
    if not metric_lines:
        return ""
    try:
        from app.services.owner_query_service import _call_claude, _log_usage, HAIKU_MODEL, _SECURITY_BLOCK
        system_prompt = (
            "You are writing a short executive summary paragraph (2-3 sentences) for a "
            "business performance comparison PDF report. Use ONLY the figures given in "
            "the <data> block. Do not add, estimate, or infer any numbers not present in "
            "the data. Write in plain, direct business English. No markdown.\n" + _SECURITY_BLOCK
        )
        user_content = "<data>" + " | ".join(metric_lines) + "</data>"
        text, in_tok, out_tok = _call_claude(HAIKU_MODEL, system_prompt, user_content, max_tokens=200)
        _log_usage(db, org_id, "owner_pdf_comparison_summary", HAIKU_MODEL, in_tok, out_tok)
        return (text or "").strip()[:600]
    except Exception as exc:
        logger.warning("_generate_comparison_summary failed org=%s: %s", org_id, exc)
        return ""


def build_comparison_pdf(
    db: Any,
    org_id: str,
    provider_names: list[str],
    date_from: Optional[date],
    date_to: Optional[date],
) -> tuple[Optional[bytes], dict]:
    """
    Side-by-side table of all key metrics for the requested period vs the
    immediately preceding period of equal length (see _prior_period), plus
    a Haiku-generated executive summary paragraph.
    """
    try:
        if not date_from or not date_to:
            return None, {"reason": "No date range was resolved for this report."}

        providers = _resolve_provider_names(db, org_id, provider_names)
        if "opsra_orders" not in providers:
            providers = ["opsra_orders"] + providers

        prior_from, prior_to = _prior_period(date_from, date_to)

        org_name = _get_org_name(db, org_id)
        current_label = _human_range(date_from, date_to)
        prior_label = _human_range(prior_from, prior_to)

        comparison_rows = ""
        any_data = False
        metric_lines_for_summary: list[str] = []

        for name in providers:
            provider = get_provider(name)
            if provider is None:
                continue
            current = provider.get_summary(db, org_id, date_from, date_to)
            if not (isinstance(current, dict) and current.get("available")):
                continue
            prior = provider.get_summary(db, org_id, prior_from, prior_to)
            prior_available = isinstance(prior, dict) and prior.get("available")

            any_data = True
            caps = get_provider_capabilities(name)
            label = caps.get("label", name.replace("_", " ").title())

            numeric_keys = [
                k for k, v in current.items()
                if isinstance(v, (int, float)) and k != "available"
            ]
            comparison_rows += f'<tr><td colspan="4"><strong>{label}</strong></td></tr>'
            for key in numeric_keys:
                cur_val = current.get(key, 0) or 0
                prior_val = (prior.get(key, 0) if prior_available else 0) or 0
                change = cur_val - prior_val
                if prior_val:
                    change_pct = change / prior_val * 100
                else:
                    change_pct = 100.0 if cur_val else 0.0
                arrow = "\u25b2" if change > 0 else ("\u25bc" if change < 0 else "\u2014")
                metric_label = key.replace("_", " ").title()
                comparison_rows += (
                    f"<tr><td>{metric_label}</td><td>{prior_val}</td><td>{cur_val}</td>"
                    f"<td>{arrow} {abs(round(change_pct, 1))}%</td></tr>"
                )
                metric_lines_for_summary.append(
                    f"{metric_label}: {prior_val} \u2192 {cur_val} "
                    f"({arrow}{abs(round(change_pct, 1))}%)"
                )

        if not any_data:
            return None, {"reason": "No data was available for either period."}

        exec_summary = _generate_comparison_summary(db, org_id, metric_lines_for_summary)

        body = f"<h2>\U0001F4C8 {prior_label} vs {current_label}</h2>"
        body += (
            "<table><tr><th>Metric</th><th>Previous</th><th>Current</th><th>Change</th></tr>"
            f"{comparison_rows}</table>"
        )
        if exec_summary:
            body += f"<h2>Summary</h2><p>{exec_summary}</p>"

        html = _base_html(
            f"{org_name} \u2014 Performance Comparison",
            f"{prior_label} vs {current_label}",
            body,
        )
        pdf_bytes = _render_pdf(html)
        if not pdf_bytes:
            return None, {"reason": "PDF generation failed."}

        return pdf_bytes, {"label": f"Performance Comparison ({current_label})"}

    except Exception as exc:
        logger.error("build_comparison_pdf failed org=%s: %s", org_id, exc)
        return None, {"reason": "Could not build the report right now."}
